### PR TITLE
Weather

### PR DESCRIPTION
**Pull request by Myrdden**
Adds endpoint to get weather from darksky API (#4), also has a bunch of setup for a Jest testing suite as I happened to be on that branch when the lesson took place.

### CODE REVIEW

**Comment by Jake0Miller** [comment]
Needs .gitignore

**Comment by Jake0Miller** [comment]
You have a location model, but when you retrieve a forecast you look up a location and then throw it away without saving it in the database.

Can you use what you've already written in your last PR to check if the location is already stored (instead of always making an API call), and then only do the API call if the location is not stored locally?

**Comment by Myrdden** [comment]
> You have a location model, but when you retrieve a forecast you look up a location and then throw it away without saving it in the database.
> 
> Can you use what you've already written in your last PR to check if the location is already stored (instead of always making an API call), and then only do the API call if the location is not stored locally?

The location model is used in storing a user's favourited locations. There's not really a point in storing a forecast in the database, unless you happen to live somewhere where the weather literally never changes.

**Comment by Myrdden** [comment]
All functionality merged on favourites branch...

**Pull request closed without merging**
